

public enum TokenType {
    MOD_TOK, ID_TOK, ASSIGN_TOK, BEGIN_TOK, SEMIC_TOK, PERIOD_TOK, IF_TOK, THEN_TOK, ELSE_TOK, LITINT_TOK,WHILE_TOK, DO_TOK, WRITEINT_TOK, REPEAT_TOK, UNTIL_TOK, LE_TOK, LT_TOK, GE_TOK, GT_TOK, EQ_TOK, NE_TOK, ADD_TOK, SUB_TOK, MUL_TOK, DIV_TOK, END_TOK, LPAREN_TOK, RPAREN_TOK, EOS_TOK
}
